language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
install:
  - npm install -g firebase-tools
branches:
  only:
  - master
script:
  - npm install
  - npm run lint
  - npm run generate
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --project familytree-hub
